spring.application.name=SecondHandTransaction
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssXXX
# Server
server.port=${PORT:8080}
# MySQL DataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:192.168.56.102}:${MYSQL_PORT:3306}/${MYSQL_NAME:SecondHandPlatform}?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
spring.datasource.username=${MYSQL_USER:SecondHand}
spring.datasource.password=${MYSQL_PASS:StrongPass}
# --- Logging ---
logging.level.root=INFO
logging.level.org.springframework.security=INFO
