spring.application.name=SecondHandTransaction
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssXXX

# Server
server.port=${PORT:8080}

# PostgreSQL Database（Neon Cloud）
spring.datasource.url=jdbc:postgresql://ep-lingering-unit-amw4168n-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VsFa7Yhy6WZp

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 启动时自动更新表结构（不删数据）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

# Logging
logging.level.root=INFO
logging.level.org.springframework.security=INFO
